### ISSUE TITLE
Can you show me how to set permissions? I can't seem to get it right.

### ISSUE THREAD

**Issue by joey-goodjob** [v-3/notion-server#1]
Can you show me how to set permissions? I can't seem to get it right.

**Comment by v-3** [comment]
Of course! Here's how I did it. 

1. Go to [Notion webpage](https://www.notion.so/profile/integrations) and create a new integration
2. Give it permission to read, write, and insert content. Based on your use case, you can also give it permission to read and add comments
3. I also gave it the capability to read user information
4. Copy the secret key and use it in your. env file for the server as well as in your Claude config
5. Finally, permission in the Notion app is managed at the page level. For pages that you want Claude to access, click on (...) > connections > (your integration) (see below)
<img width="462" alt="Screenshot 2024-12-29 at 10 01 41 PM" src="https://github.com/user-attachments/assets/d800378d-45d7-498a-8ab9-2408f8b243fd" />

Hope this helps
